const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Tilemap,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.EightDir.Acts.SetDefaultControls,
		C3.Behaviors.scrollto.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{Variable1: 0},
	{Solid: 0},
	{Door: 0},
	{Door1InteractOutside: 0},
	{Door2: 0},
	{Door2InteractOutside: 0},
	{Door3: 0},
	{Door3InteractOutSide: 0},
	{Door1InteractInside: 0},
	{Door2InteractInside: 0},
	{Door3InteractInside: 0},
	{Door4InteractOutSide: 0},
	{Door4InteractInside: 0},
	{Door4: 0},
	{MakeyMakey: 0},
	{MakeyInteractOutSide: 0},
	{Puzzle1Interact: 0},
	{Puzzle2Interact: 0},
	{Puzzle3Interact: 0},
	{FreedomDoor: 0},
	{FreedomDoorInteract: 0},
	{barrier: 0},
	{numberLock: 0},
	{txt_1: 0},
	{txt_2: 0},
	{txt_3: 0},
	{txt_4: 0},
	{DoorUnlockText: 0},
	{Tilemap: 0},
	{Tilemap2: 0},
	{Sprite5: 0},
	{PuzzleNote1: 0},
	{PuzzleNote2: 0},
	{PuzzleNote3: 0},
	{PuzzleNote4: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{isUnlock1: 0},
	{isUnlock2: 0},
	{isUnlock3: 0},
	{isUnlock4: 0},
	{isUnlock5: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{Tween: 0},
	{Player: 0},
	{t: 0},
	{orig_width: 0},
	{FrontOutline: 0},
	{BackOutline: 0},
	{Mouse: 0},
	{Einteract: 0},
	{KeyCode: 0},
	{Keyboard: 0},
	{id: 0},
	{indicater: 0},
	{LocalStorage: 0},
	{Shapes: 0},
	{th: 0},
	{click: 0},
	{hands: 0},
	{change: 0},
	{Sprite: 0},
	{Big_X: 0},
	{Button: 0},
	{Stool: 0},
	{clue: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{TiledBackground: 0},
	{Audio: 0},
	{Outside: 0},
	{Carpet: 0},
	{Text: 0},
	{Sprite4: 0},
	{st2nd3rd: 0},
	{control: 0},
	{p2_image2: 0},
	{Text2: 0},
	{Text3: 0},
	{Test1: 0},
	{number1: 0},
	{number2: 0},
	{number3: 0},
	{correct1: 0},
	{correct2: 0},
	{correct3: 0},
	{corretBool1: 0},
	{corretBool2: 0},
	{corretBool3: 0},
	{isPuzzles1Done: 0},
	{number4: 0},
	{number5: 0},
	{number6: 0},
	{correct4: 0},
	{correct5: 0},
	{correct6: 0},
	{corretBool4: 0},
	{corretBool5: 0},
	{corretBool6: 0},
	{isPuzzles2Done: 0},
	{number7: 0},
	{number8: 0},
	{number9: 0},
	{correct7: 0},
	{correct8: 0},
	{correct9: 0},
	{corretBool7: 0},
	{corretBool8: 0},
	{corretBool9: 0},
	{isPuzzles3Done: 0},
	{number10: 0},
	{number11: 0},
	{number12: 0},
	{correct10: 0},
	{correct11: 0},
	{correct12: 0},
	{corretBool10: 0},
	{corretBool11: 0},
	{corretBool12: 0},
	{isPuzzles4Done: 0},
	{number13: 0},
	{number14: 0},
	{number15: 0},
	{number16: 0},
	{correct13: 0},
	{correct14: 0},
	{correct15: 0},
	{correct16: 0},
	{corretBool13: 0},
	{corretBool14: 0},
	{corretBool15: 0},
	{correctBool16: 0},
	{isPuzzles5Done: 0}
];

self.InstanceType = {
	Door: class extends self.ISpriteInstance {},
	Door1InteractOutside: class extends self.ISpriteInstance {},
	Door2: class extends self.ISpriteInstance {},
	Door2InteractOutside: class extends self.ISpriteInstance {},
	Door3: class extends self.ISpriteInstance {},
	Door3InteractOutSide: class extends self.ISpriteInstance {},
	Door1InteractInside: class extends self.ISpriteInstance {},
	Door2InteractInside: class extends self.ISpriteInstance {},
	Door3InteractInside: class extends self.ISpriteInstance {},
	Door4InteractOutSide: class extends self.ISpriteInstance {},
	Door4InteractInside: class extends self.ISpriteInstance {},
	Door4: class extends self.ISpriteInstance {},
	MakeyMakey: class extends self.ISpriteInstance {},
	MakeyInteractOutSide: class extends self.ISpriteInstance {},
	Puzzle1Interact: class extends self.ISpriteInstance {},
	Puzzle2Interact: class extends self.ISpriteInstance {},
	Puzzle3Interact: class extends self.ISpriteInstance {},
	FreedomDoor: class extends self.ISpriteInstance {},
	FreedomDoorInteract: class extends self.ISpriteInstance {},
	barrier: class extends self.ISpriteInstance {},
	txt_1: class extends self.ITextInstance {},
	txt_2: class extends self.ITextInstance {},
	txt_3: class extends self.ITextInstance {},
	txt_4: class extends self.ITextInstance {},
	DoorUnlockText: class extends self.ITextInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	PuzzleNote1: class extends self.ISpriteInstance {},
	PuzzleNote2: class extends self.ISpriteInstance {},
	PuzzleNote3: class extends self.ISpriteInstance {},
	PuzzleNote4: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	FrontOutline: class extends self.ISpriteInstance {},
	BackOutline: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Einteract: class extends self.ISpriteInstance {},
	KeyCode: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	indicater: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Shapes: class extends self.ISpriteInstance {},
	th: class extends self.ISpriteInstance {},
	hands: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Big_X: class extends self.ISpriteInstance {},
	Button: class extends self.ISpriteInstance {},
	Stool: class extends self.ISpriteInstance {},
	clue: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	Outside: class extends self.ITiledBackgroundInstance {},
	Carpet: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	st2nd3rd: class extends self.ISpriteInstance {},
	control: class extends self.ITextInstance {},
	p2_image2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {}
}